# Site settings
title: Freelancer
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 74A8DC #80B3FF
  secondary: BF0000 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Brad Foster
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fosterthebradly
  - title: facebook
    url: https://www.facebook.com/brad.foster.5
  - title: stack-overflow
    url: http://stackoverflow.com/users/4971292/btf5048
  - title: github
    url: https://github.com/btf5048

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
